---
# tasks file for docker_jenkins

- name: Setup docker environment
  include: setup.yml

- name: Build docker jenkins image
  docker_image:
    path: 
    name: 
    state: present

- name: Create docker jenkins container
  docker_container:
    name: 
    image: 
    published_ports:
      - "50000:50000"
    restart_policy: always

- name: Install dependencies for jenkins_job module
  include: dependencies.yml

- name: Wait for jenkins to come up
  uri:
    url: 
  register: jenkins_url_result
  until: jenkins_url_result.status == 200
  retries: 5
  delay: 10