---
- name: Create directory
  file:
    path: 
    state: directory

- name: Copy files to server
  copy:
    src: files/plugins.txt
    dest: 

- name: Copy templates to server
  template:
    src: "templates/{{ item }}.j2"
    dest: "{{ docker_jenkins_home }}/{{ item }}"
  with_items:
    - Dockerfile
    - security.groovy